version: "3.7"
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - envoymesh
    expose:
      - "8123"
    ports:
      - "8123:5050"
    deploy:
      mode: replicated
      replicas: ${NUM_SERVER_REPLICAS}

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - envoymesh
    deploy:
      mode: replicated
      replicas: ${NUM_CLIENT_REPLICAS}

  extauth:
    build:
      context: .
      dockerfile: Dockerfile.extauth
    networks:
      - envoymesh
    expose:
      - "4040"
    ports:
      - "4040:4040"
    deploy:
      mode: replicated
      replicas: ${NUM_AUTH_REPLICAS}

  extauth-goraza:
    build:
      context: .
      dockerfile: Dockerfile.extauth-goraza
    networks:
      - envoymesh
    expose:
      - "4041"
    ports:
      - "4041:4041"
    volumes:
      - ./goraza.conf:/goraza/goraza.conf
    deploy:
      mode: replicated
      replicas: ${NUM_AUTH_GORAZA_REPLICAS}
      
  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    volumes:
      - ${ENVOY_YAML}:/etc/envoy.yaml
      - ./logs:/logs
    networks:
      - envoymesh
    expose:
      - "8888"
      - "1337"
    ports:
      - "8888:8888"
      - "1337:1337"

networks:
  envoymesh: {}
